# Generated by Django 4.1.2 on 2023-02-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/man.png', null=True, upload_to=''),
        ),
    ]
