# Generated by Django 4.1.2 on 2023-01-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_created_employee_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='messages', to='employee.employee'),
        ),
    ]
