# Generated by Django 4.1.2 on 2023-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_message_recipient_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='messages', to='employee.employee'),
        ),
    ]
