# Generated by Django 4.1.2 on 2023-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_message_recipient_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('vice_manager', 'Vice Manager'), ('Barreessaa', 'Barreessaa')], max_length=100, null=True),
        ),
    ]
