# Generated by Django 4.1.2 on 2023-01-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
