# Generated by Django 4.1.2 on 2023-02-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_registration_number', models.BigIntegerField(blank=True, null=True)),
                ('birth_uniques_number', models.BigIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'sex': 'male'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kebele.resident')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'sex': 'female'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='kebele.resident')),
            ],
        ),
    ]
