# Generated by Django 4.1.2 on 2023-01-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0002_businessowner_created_businessowner_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='is_here',
        ),
    ]
