# Generated by Django 4.1.2 on 2023-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0002_alter_address_options_alter_resident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='sex',
            field=models.CharField(blank=True, choices=[('Dhiira', 'Dhiira'), ('Dhalaa', 'Dhalaa')], max_length=20, null=True),
        ),
    ]
