# Generated by Django 4.1.2 on 2023-02-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0002_birthcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='father',
            field=models.OneToOneField(blank=True, limit_choices_to={'sex': 'Male'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kebele.resident'),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='mother',
            field=models.OneToOneField(blank=True, limit_choices_to={'sex': 'Female'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='kebele.resident'),
        ),
    ]
