# Generated by Django 4.1.2 on 2023-01-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0003_alter_resident_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='female_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='male_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
