# Generated by Django 4.1.2 on 2023-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0003_remove_resident_is_here'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KebeleLand',
        ),
        migrations.AddField(
            model_name='idcard',
            name='emergency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='emergency_contact',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='VitalData',
        ),
    ]
