# Generated by Django 4.1.2 on 2023-02-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0003_alter_birthcertificate_father_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthcertificate',
            old_name='birth_uniques_number',
            new_name='birth_unique_number',
        ),
    ]
