# Generated by Django 4.1.2 on 2023-02-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0004_delete_kebeleland_idcard_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='emergency_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
