# Generated by Django 4.1.3 on 2023-01-31 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0005_address_zone_alter_idcard_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebelehouse',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
