# Generated by Django 4.1.2 on 2023-02-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0006_alter_address_hnum_alter_resident_edu_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='house',
        ),
    ]
