# Generated by Django 4.1.3 on 2023-01-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0006_alter_kebelehouse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebelehouse',
            name='resident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kebele.resident'),
        ),
    ]
