# Generated by Django 4.1.2 on 2023-02-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0007_remove_family_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='nationality',
            field=models.CharField(blank=True, default='Ethiopian', max_length=100, null=True),
        ),
    ]
