# Generated by Django 4.1.2 on 2023-02-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebele', '0009_resident_resident_id_alter_birthcertificate_mother_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='id_number',
        ),
    ]
